# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d36cd184860f53c73d110beb5766c591653847c874c2565ee02a0a60ecc1582e684686e8c7d1f1a58171bd05dffc54144d2a37f5ff137377f351694eb15bb1a1

test:
  secret_key_base: 1b331c73aacb6ee6dca5fee49521352386096140691f1c4cf15c1ad84af9a1431ff0eeeb15a63ac30cd5e9f1069e5b8ebdcd185edaea5459e3c6842ac14266bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
